export const DisplayApplicationInfo = {
    APPLICATION_REQUEST: 'APPLICATION_REQUEST',
    APPLICATION_SUCCESS: 'APPLICATION_SUCCESS',
    APPLICATION_FAILURE: 'APPLICATION_FAILURE',

    APPLICATION_LOG_REQUEST: 'APPLICATION_LOG_REQUEST',
    APPLICATION_LOG_SUCCESS: 'APPLICATION_LOG_SUCCESS',
    APPLICATION_LOG_FAILURE: 'APPLICATION_LOG_FAILURE',
};